version: "3"

services:

  dangdang-mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dangdang"
      MYSQL_HOST: "%"
      MYSQL_USER: "ssafy"
      MYSQL_PASSWORD: "ssafyborissafy"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: /home/ubuntu/mysql
        target: /var/lib/mysql
    restart: always
    networks:
      - dangdang_network

  dangdang-redis:
    image: redis:6.2.6
    command: redis-server --port 6379
    ports:
      - 6379:6379
    restart: always
    networks:
      - dangdang_network

  dangdang-mongodb:
    image: mongo:5
    ports:
      - 27017:27017
    restart: always
    volumes:
      - type: bind
        source: /home/ubuntu/mongodb/data
        target: /data/db
    networks:
      - dangdang_network
    command: mongod

  dangdang-kms:
    image: kurento/kurento-media-server:latest
    restart: always
    volumes:
      - type: bind
        source: /home/ubuntu/data/videos
        target: /tmp
      # network_mode: host
    expose:
      - 8888
    ports:
      - 8888:8888
      - 5000-5050:5000-5050/udp
    environment:
      - GST_DEBUG=2,Kurento*:5
    networks:
      - dangdang_network

volumes:
  kms_data:

networks:
  dangdang_network:
    driver: bridge
    external:
      name: dangdang_network